const NEW_ORDER = "NEW_ORDER";
const CUSTOMER_COMFORMATION = "CUSTOMER_COMFORMATION";
const CUSTOMER_COMFORMED = "CUSTOMER_COMFORMED";

export { NEW_ORDER, CUSTOMER_COMFORMATION,CUSTOMER_COMFORMED };
